language: php

php:
  - 5.6
  - 7.0

before_script:
  - echo "extension = mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer self-update
  - composer --prefer-source install

services: mongodb

script: bin/phpunit